### ISSUE TITLE
tarea infografía 

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/infografia-saul19bautista#2]
[INFOGRAFIA SISTEMAS NUMERICOS_SAUL LOPEZ BAUTISTA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-saul19bautista/files/7126128/INFOGRAFIA.SISTEMAS.NUMERICOS_SAUL.LOPEZ.BAUTISTA.pdf)

**Comment by josealfredo79** [comment]
Aqui debe ir quien  califico de acuerdo a rúbrica

**Comment by irving1613** [comment]
La infografia esta bien desarrollada aunque falta bibliografia.
**Calificacion: 18**

**Comment by josealfredo79** [comment]
Bien hecho y revisado
